tester: checkIfNotWhiteSpace.c checkIfWhiteSpace.c countWords.c firstNonSpace.c readUserInput.c wordEnd.c copy.c tokenize.c printTokens.c freeTokens.c initHistory.c addHistory.c getHistory.c printHistory.c freeHistory.c
	gcc -o tester checkIfNotWhiteSpace.c checkIfWhiteSpace.c countWords.c firstNonSpace.c readUserInput.c wordEnd.c copy.c tokenize.c printTokens.c freeTokens.c initHistory.c addHistory.c getHistory.c printHistory.c freeHistory.c


