tester: checkIfNotWhiteSpace.c checkIfWhiteSpace.c countWords.c firstNonSpace.c readUserInput.c wordEnd.c copy.c tokenize.c printTokens.c freeTokens.c
	gcc -o tester checkIfNotWhiteSpace.c checkIfWhiteSpace.c countWords.c firstNonSpace.c readUserInput.c wordEnd.c copy.c tokenize.c printTokens.c freeTokens.c
