tester: checkIfNotWhiteSpace.c checkIfWhiteSpace.c countWords.c firstNonSpace.c readUserInput.c wordEnd.c
	gcc -o tester checkIfNotWhiteSpace.c checkIfWhiteSpace.c countWords.c firstNonSpace.c readUserInput.c wordEnd.c 
